name: CI

on: [push, pull_request]

jobs:
  build:
    name: Native Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [buster-tdlib1.6.0]
    container: hectorvent/tg2sip-builder:${{ matrix.tag }}

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: |
        cmake -DCMAKE_BUILD_TYPE=Release .
        cmake --build .

    - uses: actions/upload-artifact@v2
      with:
        name: tg2sip_${{ matrix.tag }}
        path: |
          build/tg2sip
          build/gen_db
          settings.ini
